/// <reference path="../config/scene.ts" />
/// <reference path="../objects/game.ts" />
/// <reference path="../objects/Label.ts" />
/// <reference path="../objects/Button.ts" />
/// <reference path="../objects/Scene.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/ocean.ts" />
/// <reference path="../objects/island.ts" />
/// <reference path="../objects/Plane.ts" />
/// <reference path="../scenes/start.ts" />
/// <reference path="../scenes/play.ts" />
/// <reference path="../scenes/over.ts" />
//# sourceMappingURL=_references.js.map